# Generated by Django 4.2.1 on 2023-05-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappinessAPP', '0004_alter_members_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HappinessAPP.teams'),
        ),
    ]
